### ISSUE TITLE
Steps to compile 

### ISSUE THREAD

**Issue by alexandredenes** [itarato/GraphMind#1]
Hello,

I'm trying to compile GraphMind on my machine. Having Flex 4 SDK and Eclipse Helios. 

Got some issues about png paths among several Embed tags but that's ok now. Create GraphMind.swf but when I run it on Flash Player it shows nothing.

The command used to compile was

mxmlc GraphMind.mxml -output=../bin/MindMap.swf -library-path+=../libs/ -target-player=10.0.0

Is there something else that I should do to compile the application?

Thanks.

**Comment by alexandredenes** [comment]
Hi. 

Found the error. Just had to staticaly link the framework RSLs. Flex 4 do dynamic link by default.

**Comment by itarato** [comment]
Hi Alexanderedenes,

Well, I haven't tried to compile it with SDK4. One thing is sure, it only works correctly with a deployed Drupal installation. You can read about this at: http://www.drupal.org/project/graphmind
Please, tell me, what do you think about the code? I didn't have the proper time to do a thorough refactoring, so it has some ugly parts. But as far as I can get some time I will continue.
